name: Go
on: [push,pull_request]
jobs:

  test2:
    name: Test2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          set -e
          cd "${GITHUB_WORKSPACE}" || exit 1
          
          TEMP_PATH="$(mktemp -d)"
          PATH="${TEMP_PATH}:$PATH"
          
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b "${TEMP_PATH}" 2>&1
          reviredog --version
  test:
    permissions:
      contents: read
    name: Test
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
      with:
        fetch-depth: 50 # Need git history for testing.

    - uses: actions/setup-go@v5
      with:
        go-version-file: "go.mod"

    - name: Test
      run: go test -v -race -coverpkg=./... -coverprofile=coverage.txt ./...

    - uses: codecov/codecov-action@v4
